# Example playbook
---
- name: enable features
  hosts: demo_nexus_switches
  connection: local
  gather_facts: no

  vars_files:
    - external_vars.yml

  tasks:

  - name: Enable feature HSRP and BFD
    nxos_config:
      lines:
        - no feature hsrp
        - no feature bfd
      save: no
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: "{{ transport }}"

