# Example playbook
---
- name: enable nxapi feature
  hosts: demo_nexus_switches
  connection: local
  gather_facts: no

  vars_files:
    - external_vars.yml

  tasks:

  - name: Make sure NXAPI is on
    nxos_command:
      commands:
        - conf t
        - feature nxapi
        - nxapi https port 443
        - end
        - copy run st
      save: yes
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: "{{ transport }}"