# Example playbook
---
- name: enable nxapi feature
  hosts: demo_nexus_switches
  connection: local
  gather_facts: no

  vars_files:
    - external_vars.yml

  tasks:

  - name: Make sure NXAPI is on
    nxos_config:
      lines:
        - feature nxapi
        - nxapi https 443
      save: yes
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: "{{ transport }}"