# Example playbook
---
- name: enable features
  hosts: demo_nexus_switches
  connection: local
  gather_facts: yes

  vars_files:
    - external_vars.yml

  tasks:

  - name: Enable HSRP and BFD
    nxos_config:
      lines:
        - feature hsrp
        - feature bfd
      save: yes
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: "{{ transport }}"

