# Playbook to get facts from NXOS devices
---
- name: Get facts from NXOS demo devices
  hosts: demo_nexus_switches
  connection: local
  gather_facts: no

  vars_files:
    - external_vars.yml
  
  tasks:
  - name: Get interfaces of NXOS device
    nxos_facts:
      host: "{{ inventory_hostname }}"
      gather_subset:
        - interfaces