# Example playbook
---
- name: Change VLANs on switches
  hosts: demo_nexus_switches
  connection: local
  gather_facts: no

  vars_files:
    - external_vars.yml

  tasks:

  - name: Make sure vlan 100 is present
    nxos_vlan:
      vlan_id: 100
      name: web
      state: absent
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: "{{ transport }}"
    notify: save config
  
  - name: Make sure vlan 200 is present
    nxos_vlan:
      vlan_id: 200
      name: database
      state: absent
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: "{{ transport }}"
    notify: save config

  handlers:
    - name: save config
      nxos_conmmand:
        commands:
          - copy running start