# Example playbook
---
- name: add vlan 100 to all switches
  hosts: demo_nexus_switches
  connection: local
  gather_facts: no

  vars_files:
    - external_vars.yml

  tasks:

  - name: Make sure vlan 100 doesn't exist
    nxos_vlan:
      vlan_id: 100
      state: present
      host: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      transport: "{{ transport }}"

 
